name: infrastructure

on:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "SHA to deploy"
        required: true
        type: string

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: false

env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

# TODO: Skip if no changes in directory
jobs:
  lint_shell:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions: {}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo apt install shellcheck
      - name: Run shellcheck
        run: ./s/shellcheck

  build_bot_container:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: "{{defaultContext}}:bot"
          push: true
          file: "Dockerfile"
          tags: ghcr.io/kaiko-ai/kodiak:${{ env.SHA }}
          cache-from: type=gha,scope=kodiak
          cache-to: type=gha,scope=kodiak,mode=max
          provenance: false
          sbom: false

  build_api_container:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: "{{defaultContext}}:web_api"
          push: true
          file: "Dockerfile"
          tags: ghcr.io/kaiko-ai/kodiak-web-api:${{ env.SHA }}
          cache-from: type=gha,scope=kodiak-web-api
          cache-to: type=gha,scope=kodiak-web-api,mode=max
          provenance: false
          sbom: false
          build-args: |
            GIT_SHA=${{ env.SHA }}

  build_web_ui_container:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: "{{defaultContext}}:web_ui"
          push: true
          file: "Dockerfile"
          tags: ghcr.io/kaiko-ai/kodiak-web-ui:${{ env.SHA }}
          cache-from: type=gha,scope=kodiak-web-ui
          cache-to: type=gha,scope=kodiak-web-ui,mode=max
          provenance: false
          sbom: false
          build-args: |
            GIT_SHA=${{ env.SHA }}
